{
 "title": "Nebius Object Storage",
 "description": "Nebius Object Storage Overview.",
 "tags": [
  "Nebius",
  "Object Storage"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "bucket",
    "query": "label_values(buckets_stat_quantity, bucket)"
   }
  ]
 },
 "panels": [
  { "title": "Storage space", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Traffic",
   "type": "timeseries",
   "description": "Data transfer speed to and from storage.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(bucket) (rate(http_bytes_sent{bucket=~\"$bucket\"}[$__rate_interval])) OR on() vector(0)",
     "legendFormat": "Download {{bucket}}"
    },
    {
     "expr": "sum by(bucket) (rate(http_bytes_received{bucket=~\"$bucket\"}[$__rate_interval])) OR on() vector(0)",
     "legendFormat": "Upload {{bucket}}"
    }
   ]
  },
  {
   "title": "Total bucket size",
   "type": "timeseries",
   "description": "Storage space used by all objects in a bucket.",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(bucket) (max by(bucket, counter) (last_over_time(buckets_stat_size{bucket=~\"$bucket\"}[1m])))",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "Space by storage class",
   "type": "timeseries",
   "description": "Amount of storage used by objects in different storage classes.",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(bucket) (max by(bucket, counter) (last_over_time(buckets_stat_size{bucket=~\"$bucket\",storage_class=\"STANDARD\"}[1m])))",
     "legendFormat": "{{bucket}} Standard"
    },
    {
     "expr": "sum by(bucket) (max by(bucket, counter) (last_over_time(buckets_stat_size{bucket=~\"$bucket\",storage_class=\"ENHANCED_THROUGHPUT\"}[1m])))",
     "legendFormat": "{{bucket}} Enhanced Throughput"
    }
   ]
  },
  { "title": "Requests for $bucket", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 }, "repeat": "bucket" },
  {
   "title": "Read requests",
   "type": "timeseries",
   "description": "Number of requests made to retrieve object content from a bucket. ",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(handler) (rate(request_rate{bucket=\"$bucket\", operation_type=\"read\"}[$__rate_interval]))",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Modify requests",
   "type": "timeseries",
   "description": "Number of requests made to upload objects or modify object content. ",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(handler) (rate(request_rate{bucket=\"$bucket\", operation_type=\"mutate\"}[$__rate_interval]))",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "API errors",
   "type": "timeseries",
   "description": "Number of errors when accessing S3 API. Number of errors per 5 minutes.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(handler, http_code, api_error_code) (increase(http_errors_total{bucket=\"$bucket\"}[5m]))",
     "legendFormat": "{{handler}}:{{http_code}}:{{api_error_code}}"
    }
   ]
  },
  { "title": "Objects statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Object counts",
   "type": "timeseries",
   "description": "Number of objects. Single, multipart objects, and incomplete multipart uploads are counted separately.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(bucket) (max by(bucket, counter) (last_over_time(buckets_stat_quantity{bucket=~\"$bucket\", counter=\"simple_objects\"}[1m])))",
     "legendFormat": "{{bucket}} Simple objects"
    },
    {
     "expr": "sum by(bucket) (max by(bucket, counter) (last_over_time(buckets_stat_quantity{bucket=~\"$bucket\", counter=\"multipart_objects\"}[1m])))",
     "legendFormat": "{{bucket}} Multipart objects"
    },
    {
     "expr": "sum by(bucket) (max by(bucket, counter) (last_over_time(buckets_stat_quantity{bucket=~\"$bucket\", counter=\"inflight_parts\"}[1m])))",
     "legendFormat": "{{bucket}} Multipart uploads"
    }
   ]
  },
  {
   "title": "Space by object type",
   "type": "timeseries",
   "description": "Amount of storage used by objects of different types.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(bucket) (max by(bucket, counter) (last_over_time(buckets_stat_size{bucket=~\"$bucket\", counter=\"simple_objects\"}[1m])))",
     "legendFormat": "{{bucket}} Simple objects"
    },
    {
     "expr": "sum by(bucket) (max by(bucket, counter) (last_over_time(buckets_stat_size{bucket=~\"$bucket\", counter=\"multipart_objects\"}[1m])))",
     "legendFormat": "{{bucket}} Multipart objects"
    },
    {
     "expr": "sum by(bucket) (max by(bucket, counter) (last_over_time(buckets_stat_size{bucket=~\"$bucket\", counter=\"inflight_parts\"}[1m])))",
     "legendFormat": "{{bucket}} Multipart uploads"
    }
   ]
  },
  {
   "title": "Object counts by storage class",
   "type": "timeseries",
   "description": "Number of objects stored in different storage classes.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(bucket) (max by(bucket, counter) (last_over_time(buckets_stat_quantity{bucket=~\"$bucket\", storage_class=\"STANDARD\"}[1m])))",
     "legendFormat": "{{bucket}} Standard"
    },
    {
     "expr": "sum by(bucket) (max by(bucket, counter) (last_over_time(buckets_stat_quantity{bucket=~\"$bucket\", storage_class=\"ENHANCED_THROUGHPUT\"}[1m])))",
     "legendFormat": "{{bucket}} Enhanced Throughput"
    }
   ]
  }
 ]
}