{
 "title": "Nebius Monitoring",
 "description": "Dashboard provides an overview of the Nebius Monitoring. https://docs.nebius.com/observability/monitoring",
 "tags": [
  "Nebius",
  "Monitoring"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Ingest", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Ingest requests",
   "type": "timeseries",
   "description": "Number of metrics ingestion requests per second",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum (rate(requests_total{type=\"write\"}[$__rate_interval]))",
     "legendFormat": "Requests"
    },
    {
     "expr": "requests_limits{type=\"monitoring.write.throughput.requests\"}",
     "legendFormat": "Requests limit"
    }
   ]
  },
  {
   "title": "Ingest requests errors",
   "type": "timeseries",
   "description": "Number of failed metrics ingestion requests per second, by status code",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (status_code) (rate(requests_total{status_code!~\"2.*\", type=\"write\"}[$__rate_interval])) or on() vector(0)",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  { "title": "Read", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Read requests",
   "type": "timeseries",
   "description": "Number of metrics read requests per second",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum (rate(requests_total{type=\"read\"}[$__rate_interval]))",
     "legendFormat": "Requests"
    },
    {
     "expr": "requests_limits{type=\"monitoring.read.throughput.requests\"}",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "Read requests errors",
   "type": "timeseries",
   "description": "Number of failed metrics read requests per second, by status code",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (status_code) (rate(requests_total{status_code!~\"2.*\", type=\"read\"}[$__rate_interval])) or on() vector(0)",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  { "title": "Workload", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Samples ingestion rate",
   "type": "timeseries",
   "description": "Number of samples ingested per second, by type",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "rowsps" } },
   "targets": [
    {
     "expr": "sum by(type) (rate(samples_total{}[$__rate_interval])) OR on() vector(0)",
     "legendFormat": "{{type}}"
    }
   ]
  }
 ]
}